Blog_de_recetas_2023/blog/apps/recetas/urls.py
from django.urls import path
from . import views


app_name = 'recetas'


urlpatterns = [
    path('', views.ListarRecetas, name='listar'),
    path('detalle/<int:pk>', views.DetalleReceta, name='detalle'),
    path('addpost', views.AddPost, name='addpost'),
    path('comentario/delete/<int:comentario_id>', views.BorrarComentario, name='delete_comentario'),
    path('recetas/<int:pk>/edit/', views.EditarReceta, name='edit_receta'),
    path('comentario/edit/<int:comentario_id>', views.EditarComentario, name='edit_comentario'),


]

Blog_de_recetas_2023/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from .views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path('', views.home, name='home'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('recetas/', include('apps.recetas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('addpost/', views.addpost, name='addpost'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Blog_de_recetas_2023/blog/apps/recetas/models.py
from django.db import models
from django.utils import timezone
from apps.usuarios.models import Usuario

# Create your models here.




#CATEGORIA
class Categoria(models.Model):
    nombre = models.CharField(max_length=30, null=False)

    def __str__(self):
        return self.nombre

class Post(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    subtitulo = models.CharField(max_length=100, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    contenido = models.TextField(null=False)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, default='Sin categoría')
    imagenes = models.ImageField(null=True, blank=True, upload_to='recetas', default='static/post_default.png')
    publicado = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publicado',)

    def __str__(self):
        return self.titulo
        
    def delete(self, using =None, keep_parents=False):
        self.imagen.delete(self.imagen.name)
        super().delete()
            


class Receta(models.Model):
    titulo = models.CharField(max_length=50) # = VARCHAR | max_length longitud max
    subtitulo = models.CharField(max_length=100, null=True, blank=True)
    resumen = models.CharField(max_length=200, null=True)
    texto = models.TextField()
    #imagen requiere la libreria pillow
    imagenes = models.ImageField(null=True, blank=True, upload_to='recetas', default='static/post_default.png')
    fecha = models.DateTimeField(auto_now_add=True)
    categorias = models.ForeignKey(Categoria, on_delete= models.SET_NULL, null=True) # models.CASCADE
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, default=Usuario.objects.get(is_superuser=True).pk)


    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    noticia = models.ForeignKey(Receta, on_delete=models.CASCADE, related_name='comentarios')
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    usuario = models.CharField(max_length=50)


    def __str__(self):
        return self.contenido

Blog_de_recetas_2023/blog/apps/recetas/forms.py
from django import forms
from .models import Receta, Comentario


class PostForm(forms.ModelForm):


    class Meta:
        model = Receta
        fields = [
            'titulo',
            'resumen',
            'texto',
            'imagenes',
            'categorias',
        ]


class ComentarioForm(forms.ModelForm):
   
    class Meta:
        model = Comentario
        fields = [
            'contenido',
        ]
        exclude = ['usuario']
   
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)


        super(ComentarioForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.usuario = user.username



Blog_de_recetas_2023/blog/apps/recetas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from .models import Post, Categoria, Receta, Comentario, Usuario
from django.views.generic import ListView
from django.contrib import messages
from django.contrib.auth.decorators import login_required   
from django.http import Http404, HttpResponse, HttpResponseForbidden
from .forms import PostForm, ComentarioForm

# Create your views here.
def DetalleReceta(request, pk):


    n = Receta.objects.get(pk = pk) # SELECT * FROM NOTICIAS WHERE id = 1
    c = n.comentarios.all()


    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_receta' in request.POST:
        n.delete()
        return redirect('recetas:listar')
   
    #COMENTARIO
    if request.method == 'POST' and 'add_comentario' in request.POST:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.usuario = request.user
            form.save()
            return redirect('recetas:detalle', pk=pk)
    else:
        form = ComentarioForm()
   
    contexto = {
        'recetas': n,
        'comentarios': c,
        'form': form,
    }


    return render (request, 'recetas/detalle.html', contexto)


def ListarRecetas(request):
    contexto = {}
    id_categoria = request.GET.get("id", None)


    if id_categoria:
        n = Receta.objects.filter(categorias = id_categoria)
    else:
        n = Receta.objects.all() # SELECT * FROM NOTICIAS
    cat = Categoria.objects.all().order_by('nombre') #ordena por nombre
    contexto['recetas'] = n
    contexto['categorias'] = cat

        # filtrar por antiguedad asc
    antiguedad_asc = request.GET.get("antiguedad_asc")
    if antiguedad_asc:
        n = Receta.objects.all().order_by('fecha') #ordena por fecha


    # filtrar por antiguedad desc
    antiguedad_desc = request.GET.get("antiguedad_desc")
    if antiguedad_desc:
        n = Receta.objects.all().order_by('-fecha') #ordena por fecha


    # filtrar por orden alfabetico asc
    orden_asc = request.GET.get("orden_asc")
    if orden_asc:
        n = Receta.objects.all().order_by('titulo') #ordena por titulo


    # filtrar por orden alfabetico desc
    orden_desc = request.GET.get("orden_desc")
    if orden_desc:
        n = Receta.objects.all().order_by('-titulo') #ordena por titulo



    return render (request, 'recetas/listar.html', contexto)


@login_required
def AddPost(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES) ##Request files es para las imagenes


        if form.is_valid():
            recetas = form.save(commit=False)
            recetas.autor = request.user
            form.save()
            return redirect('home')
    else:
        form = PostForm()
    
    return render (request, 'recetas/addpost.html', {'form':form})



@login_required
def AddComentario(request, receta_id):


    receta = get_object_or_404(Receta, id = receta_id)  
    if request.method == 'POST':
        contenido = request.POST.get("contenido")
        usuario = request.user.username
        # creacion de comentario
        Comentario.objects.create(receta = receta, usuario = usuario, contenido = contenido)
   
    return redirect('recetas:detalle', pk = receta_id)


@login_required
def BorrarComentario(request, comentario_id):


    comentario = get_object_or_404(Comentario, id = comentario_id)  
    if comentario.usuario == request.user.username:
        comentario.delete()
   
    return redirect('recetas:detalle', pk = comentario.receta.pk)


@login_required
def EditarReceta(request, pk):
    receta = get_object_or_404(Receta, pk=pk)


    # Solo el autor puede editar la noticia
    if receta.autor != request.user:
        return HttpResponseForbidden("No tenes permiso para editar esta receta.")


    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=receta)
        if form.is_valid():
            form.save()
            return redirect('recetas:detalle', pk=pk)
    else:
        form = PostForm(instance=receta)


    context = {
        'form': form,
    }
    return render(request, 'noticias/editar.html', context)


# EDITAR COMENTARIOS
@login_required #debes estar loggeado para poder editar
def EditarComentario(request, comentario_id):
    comentario = get_object_or_404(Comentario, id=comentario_id)


    # mensaje de error si no sos el autor del comentario
    if comentario.usuario != request.user.username:
        messages.error(request, 'No tenes permiso para editar este comentario')
        return redirect('recetas:detalle', pk=comentario.receta.pk)
   
    if request.method == 'POST':
        form = ComentarioForm(request.POST, instance=comentario)
        if form.is_valid():
            form.save()
            return redirect('recetas:detalle', pk=comentario.receta.pk)
    else:
        form = ComentarioForm(instance=comentario)
   
    contexto = {
        'form':form,
        'comentario':comentario,
    }


    return render(request, 'recetas/editar_comentario.html', contexto)

Blog_de_recetas_2023/blog/templates/recetas/addpost.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block titulo %}Mi Blog {% endblock titulo %}</title>
</head>
{% block contenido %}

<body class="contenedor">

{% block titulo %}addpost{% endblock titulo %}
    <h2>Crea una receta</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock block contenido %}

</body>
</html>

Blog_de_recetas_2023/blog/templates/recetas/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Mi receta detallada</h2>
    {% if user.is_authenticated and recetas.autor == user %}
    <form method="POST" action="{% url 'recetas:detalle' pk=recetas.pk %}">
        {% csrf_token %}
        <button type="submit" name="delete_receta">BORRAR</button>
    </form>
{% endif %}

    <div class="rece">
        <img src="{{recetas.imagenes.url}}" width="30%">
        <h3>{{recetas.titulo}}</h3>
        <p>{{recetas.contenido}}</p>
        <p>{{recetas.fecha}}</p>
        <p>{{recetas.categoria}}</p>
        <p>Autor: {{recetas.autor}}</p>
        <a href="{% url 'recetas:edit_receta' pk=recetas.pk %}">Editar</a>
        <form method="POST" action="{% url 'tecetas:detalle' pk=recetas.pk %}">
            {% csrf_token %}
            <button type="submit" name="delete_receta">BORRAR</button>
        </form>
    {% endif %}
</div>
    <br>
    <h4>Comentarios</h4>
    {% for comentario in comentarios %}
        <p><strong>{{comentario.usuario}} - {{comentario.fecha_creacion}}</strong></p>
        <p>{{comentario.contenido}}</p>
        <form method="post" action="{% url 'recetas:delete_comentario' comentario.id %}">
            {% csrf_token %}
            {% if comentario.usuario == user.username %}
                <button type="submit">Borrar</button>
                <a href="{% url 'recetas:edit_comentario' comentario_id=comentario.id %}">Editar</a>
            {% endif %}
        </form>
    <br>
    {% endfor %}
    {% if user.is_authenticated %}
        <h4>Añadir comentarios</h4>
        <form method="post" action="{% url 'recetas:add_comentario' recetas.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enviar</button>
        </form>
    {% else %}
        <p>Debe iniciar sesión para dejar un comentario</p>
        <a href="{% url 'login' %}">INICIAR SESION</a>
    {% endif %}
    <a href="{% url 'recetas:listar' %}">VOLVER</a>
{% endblock contenido %}

        {% if user.is_authenticated and receta.autor == user or user.is_staff %}
    <a href="{% url 'recetas:edit_receta' pk=recetas.pk %}">Editar</a>

    {% if comentario.usuario == user.username %}
    <button type="submit">Borrar</button>
    <a href="{% url 'recetas:edit_comentario' comentario_id=comentario.id %}">Editar</a>
{% endif %}



        <a href="{% url 'recetas:listar' %}">VOLVER</a>
        <p>Autor: {{recetas.autor}}</p>
        {% if user.is_authenticated %}
        <h4>Añadir comentarios</h4>
        <form method="post" action="{% url 'recetas:add_comentario' recetas.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enviar</button>
        </form>
    {% else %}
        <p>Debe iniciar sesión para dejar un comentario</p>
        <a href="{% url 'login' %}">INICIAR SESION</a>
    {% endif %}
    <a href="{% url 'recetas:listar' %}">VOLVER</a>
    <h4>Comentarios</h4>
    {% for comentario in comentarios %}
        <p><strong>{{comentario.usuario}} - {{comentario.fecha_creacion}}</strong></p>
        <p>{{comentario.contenido}}</p>
        <form method="post" action="{% url 'recetas:delete_comentario' comentario.id %}">
            {% csrf_token %}
            {% if comentario.usuario == user.username %}
                <button type="submit">Borrar</button>
            {% endif %}
        </form>
    <br>
    {% endfor %}
    {% if user.is_authenticated and receta.autor == user or user.is_staff %}
    <a href="{% url 'recetas:edit_receta' pk=recetas.pk %}">Editar</a>

    {% if comentario.usuario == user.username %}
    <button type="submit">Borrar</button>
    <a href="{% url 'recetas:edit_comentario' comentario_id=comentario.id %}">Editar</a>
{% endif %}

    </div>
{% endblock contenido %}

Blog_de_recetas_2023/blog/templates/recetas/editar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Editar Receta</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

Blog_de_recetas_2023/blog/templates/recetas/editar_comentario.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Editar Comentario</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

Blog_de_recetas_2023/blog/templates/recetas/listar.html
</head> 
{% extends 'base.html' %}

</head>   
</main>

<h2>aca estan mis recetas !</h2>

{% block contenido %}
<main>
<div class="submenu">
    <h1><a href="{% url 'recetas:listar'%}">Listado de Todas las Recetas</a></h1> <br> <br>
</main>
    {% block Categorias %}<h3>Por Categorias</h3>{% endblock Categorias %} 
    {% for cat in categorias %}
        <a href="?id={{cat.pk}}">{{cat.nombre}}</a> <br>
    {% endfor %} <br>
    
    {% block Fecha %}<h3>Por Fecha de Publicacion</h3>{% endblock Fecha %}
    <a href="?antiguedad_asc=A">Mas antiguas primero</a> <br>   
    <a href="?antiguedad_desc=D">Mas recientes primero</a> <br>

    {% block Orden %}<h3>Por Orden Alfabético</h3>{% endblock Orden %}
    <a href="?orden_asc=1">A - Z</a> 
    <a href="?orden_desc=1">Z - A</a> <br>
</div>


{% endblock %}

{% block post %}
<nav class="contenedorpost1"><h2>xxx</h2></nav>


{% endblock %}

</main>