blog_recetas/apps/recetas/urls.py
from django.urls import path
from . import views


app_name = 'recetas'

urlpatterns = [
    path('', views.ListarRecetas, name='listar'),
    path('detalle/<int:pk>', views.DetalleReceta, name='detalle'),
    path('addReceta', views.AddReceta, name='addreceta'),
    path('comentario/add/<int:receta_id>', views.AddComentario, name='add_comentario'),
]

blog_recetas/blog_recetas/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home_recetas, name='home_recetas'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('recetas/', include('apps.recetas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    
    
      
    #parametro 1: es el texto de la url
    #parametro 2: la vista que se va a ejecutar
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


blog_recetas/apps/recetas/models.py
from django.db import models
from apps.usuarios.models import Usuario


# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Receta(models.Model):
    titulo = models.CharField(max_length=255)
    descripcion = models.TextField()
    ingredientes = models.TextField()
    instrucciones = models.TextField() 
    imagen = models.ImageField(upload_to="recetas", null=True)
    fecha_publicacion= models.DateTimeField(auto_now_add=True, editable=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL,null=True)
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, null = True)
    
    def __str__(self):
        return self.titulo
        

class Comentario(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE, related_name='comentarios')
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    usuario = models.CharField(max_length=50)

    def __str__(self):
        return self.contenido

    

blog_recetas/apps/recetas/forms.py
# forms.py en tu aplicación

from django import forms
from .models import Receta,Comentario

class AgregarRecetaForm(forms.ModelForm):
    class Meta:
        model = Receta
        fields = ['titulo', 'descripcion', 'ingredientes', 'instrucciones', 'categoria', 'imagen']

    widgets = {
        'descripcion': forms.Textarea(attrs={'rows': 3}),
        'ingredientes': forms.Textarea(attrs={'rows': 5}),
        'instrucciones': forms.Textarea(attrs={'rows': 10}),
    }
    
class ComentarioForm(forms.ModelForm):
   
    class Meta:
        model = Comentario
        fields = [
            'contenido',
        ]
        exclude = ['usuario']
   
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)


        super(ComentarioForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.usuario = user.username 

blog_recetas/apps/recetas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Receta, Categoria, Comentario
from .forms import AgregarRecetaForm, ComentarioForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.contrib import messages

def ListarRecetas(request):
      # Lógica de la vista aquí
    contexto = {}
    
    
    id_categoria= request.GET.get("id",None)

    if id_categoria:
          n = Receta.objects.filter(categoria = id_categoria)
    else:
          n = Receta.objects.all() # SELECT * FROM RECETAS
          
    cat = Categoria.objects.all().order_by('nombre') #ordena por nombre
    contexto['recetas'] = n
    contexto['categorias'] = cat
    
    #Filtra por Fecha de Publicacion
    #Ascendente
    
    antiguedad_asc = request.GET.get("antiguedad_asc")
    if antiguedad_asc:
        n = Receta.objects.all().order_by('fecha_publicacion') #ordena por fecha


    # filtrar por antiguedad desc
    
    antiguedad_desc = request.GET.get("antiguedad_desc")
    if antiguedad_desc:
        n = Receta.objects.all().order_by('-fecha_publicacion') #ordena por fecha

            
       # filtrar por orden alfabetico asc
    
    orden_asc = request.GET.get("orden_asc")
    if orden_asc:
        n = Receta.objects.all().order_by('titulo') #ordena por titulo


    # filtrar por orden alfabetico desc
    orden_desc = request.GET.get("orden_desc")
    if orden_desc:
        n = Receta.objects.all().order_by('-titulo') #ordena por titulo

      
    return render(request, 'recetas/listar.html', contexto)
    
    
def DetalleReceta(request, pk):
    
    contexto = {}

    n = Receta.objects.get(pk = pk) # SELECT * FROM NOTICIAS WHERE id = 1
    c = n.comentarios.all()
    
    contexto['receta'] = n
    
        
      #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_receta' in request.POST:
        n.delete()
        return redirect('recetas:listar')
    
    
        
    #COMENTARIO
          
    if request.method == 'POST' and 'add_comentario' in request.POST:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.usuario = request.user
            form.save()
            return redirect('recetas:detalle', pk=pk)
    else:
        form = ComentarioForm()
    
   
    contexto = {
        'receta': n,
        'comentarios': c,
        'form': form,
    }




   
    return render (request, 'recetas/detalle.html', contexto)



@login_required
def AddReceta(request):
    if request.method == 'POST':
        form = RecetaForm(request.POST or None, request.FILES) ##Request files es para las imagenes


        if form.is_valid():
            receta = form.save(commit=False)
            receta.autor = request.user
            form.save()
            return redirect('home')
    else:
        form = RecetaForm()
   
    return render (request, 'receta/addReceta.html', {'form':form})


@login_required
def AddComentario(request, receta_id):

    receta = get_object_or_404(Receta, id = receta_id)  
    if request.method == 'POST':
        contenido = request.POST.get("contenido")
        usuario = request.user.username
        # creacion de comentario
        Comentario.objects.create(receta = receta, usuario = usuario, contenido = contenido)
        
    return redirect('recetas:detalle', pk = receta_id)

blog_recetas/templates/recetas/addReceta.html
!-- templates/agregar_receta.html -->

{% extends 'base.html' %}
{% load static %}


{% block title %}Agregar Nueva Receta{% endblock %}

{% block content %}
  <h1>Agregar Nueva Receta</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar</button>
  </form>

  <a href="{% url 'lista_recetas' %}">Volver a la Lista de Recetas</a>
{% endblock %}

blog_recetas/templates/recetas/detalle.html
{% extends 'base.html' %}

{% block title %}Detalles de la Receta: {{ receta.titulo }}{% endblock %}

{% block contenido %}
  <h2>Receta</h2>
  <div>

      <h1>{{ receta.titulo }}</h1>
      <p><strong>Descripción:</strong> {{ receta.descripcion }}</p>
      <p><strong>Ingredientes:</strong> {{ receta.ingredientes }}</p>
      <p><strong>Instrucciones:</strong> {{ receta.instrucciones }}</p>
      <p><strong>Categoría:</strong> {{ receta.categoria }}</p>
      <p><strong>Autor: </strong> {{receta.autor}}</p>

      {% if user.is_authenticated and receta.autor == user or user.is_staff  %}
      <form method="POST" action="{% url 'recetas:detalle' pk=receta.pk %}">
          {% csrf_token %}
          <button type="submit" name="delete_receta">BORRAR</button>
      </form>
      {% endif %} 

      {% if user.is_authenticated %}
      <h4>Añadir comentarios</h4>
      <form method="post" action="{% url 'recetas:add_comentario' receta.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
      </form>
    {% else %}
        <p>Debe iniciar sesión para dejar un comentario</p>
        <a href="{% url 'login' %}">INICIAR SESION</a>
    {% endif %}
    
      
  </div>
{% endblock contenido %}

blog_recetas/templates/recetas/editar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Editar Receta</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

blog_recetas/templates/recetas/editar_comentario.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Editar Comentario</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

blog_recetas/templates/recetas/listar.html
<!-- templates/lista_recetas.html -->

{% extends 'base.html' %}
{% load static %}
{% block titulo %}Lista de Recetas{% endblock titulo %}
{% block contenido %}
    <h2>Listado de Recetas !</h2>
    {% for receta in recetas %} 
        <p><a href="{% url 'recetas:detalle' receta.pk %}">  <h3>{{receta.titulo}}</h3>
                 
    {% endfor %}

    <div class="submenu">
        <a href="{% url 'recetas:listar'%}">Listado de Todas las Recetas</a> <br> <br>
        {% block Categorias %}<h2>Por Categorias</h2>{% endblock Categorias %} 
        {% for cat in categorias %}
            <a href="?id={{cat.pk}}">{{cat.nombre}}</a> <br>
        {% endfor %} <br>
        
        {% block Fecha %}<h2>Por Fecha de Publicacion</h2>{% endblock Fecha %} 
        <a href="?antiguedad_asc=A">Mas antiguas primero</a> 
        <a href="?antiguedad_desc=D">Mas recientes primero</a> <br>

        {% block Orden %}<h2>Por Orden Alfabético</h2>{% endblock Orden %}
        <a href="?orden_asc=1">A - Z</a> 
        <a href="?orden_desc=1">Z - A</a> <br>
    </div>
    
    <br/>


{% endblock contenido %}
