Blog_de_recetas_2023/blog/apps/recetas/urls.py
from django.urls import path
from . import views


app_name = 'recetas'


urlpatterns = [
    path('', views.ListarRecetas, name='listar'),
    path('detalle/<int:pk>', views.DetalleReceta, name='detalle'),
    path('addpost', views.AddPost, name='addpost'),
    path('comentario/delete/<int:comentario_id>', views.BorrarComentario, name='delete_comentario'),
    path('recetas/<int:pk>/edit/', views.EditarReceta, name='edit_receta'),
    path('comentario/edit/<int:comentario_id>', views.EditarComentario, name='edit_comentario'),


]

Blog_de_recetas_2023/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from .views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path('', views.home, name='home'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('recetas/', include('apps.recetas.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('addpost/', views.addpost, name='addpost'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Blog_de_recetas_2023/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block titulo %}Mi Blog {% endblock titulo %}</title>
</head>
    {% block contenido %}
    <main><h1>Blog de recetas 2023</h1></main>
    <contenedor> <p> Las mejores recetas. </p></contenedor>
    {% endblock contenido %}
</body>
{% block nosotros %}

<nav class="contenedor2"> 
    <a href="{% url 'home' %}">VOLVER AL INICIO</a></br>
    
<a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
</nav>
{% endblock nosotros %}

{% block navb %}

<footer>    

    <nav class="contenedor3">
    <h2>Hola {{ user.username }}</h2>
 
</br><a href="{% url 'recetas:listar' %}">RECETAS</a></br>
    {% if user.is_authenticated %}

</br><a href="{% url 'addpost' %}">ADDPOST</a></br>   
</br><a href="{% url 'logout' %}">LOGOUT</a></br>
    {% else %}
</br><a href="{% url 'login' %}">LOGIN</a></br>
</br><a href="{% url 'registro' %}">REGISTRO</a>
    {% endif %}

    </nav>
    {% endblock navb %}

</footer>

</html>

Blog_de_recetas_2023/blog/templates/home.html
<!DOCTYPE html>
<html lang="es-ar">
    {% extends 'base.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<main><h1>Blog_de_recetas_2023</h1></main>
{% load static %}
{% block titulo %}Home{% endblock titulo %}
{% block contenido %}
    <h2>hola mundo</h2>

{% endblock contenido %}

<body>
    Hola mundo
</body>
</html>

Blog_de_recetas_2023/blog/templates/index.html
<!doctype html>
<html lang="es-ar">
    <head>
        <title>Blog_de_recetas_2023</title>
        {% extends 'base.html' %}


        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <main><h1>Blog_de_receeas_2023</h1></main>
        <header>
            <!-- place navbar here -->
        </header>
        <main></main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
    <h1>!!!</h1>
    <a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
    <a href="{% url 'home' %}">VOLVER AL INICIO</a>
    <a href="{% url 'recetas:listar' %}">RECETAS</a>
</html>

Blog_de_recetas_2023/blog/templates/nosotros.html
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog de recetas 2023</title>
</head>
{% extends 'base.html'%}

{% load static %}
{% block titulo %}Nosotros{% endblock titulo %}
{% block contenido %}
    <main><h1>Integrantes del Grupo N°2 Comision 6 <h1></main>
        
    <h2>
        <br>Bocek Juan<br>
        <br>Garcia Mario<br>
        <br>Montiel Sergio<br>
        <br>Rojas Agustin<br>
        
    </h2>
{% endblock contenido %}

<body>
    Sobre mi !
</body>
</html>